### ISSUE TITLE
(bug) Alert Rule does not allow the config type "Jira"

### ISSUE THREAD

**Issue by hross-frae** [PaloAltoNetworks/terraform-provider-prismacloud#111]
## Describe the bug

When configuring an alert rule notification config, it is not possible to set `jira` as config type.

## Expected behavior

Should be able to set `jira` as a config type.

## Current behavior

Validation fails when setting `jira` as a the type.

## Possible solution

- Update the go library for Prisma cloud with the Jira type: https://github.com/PaloAltoNetworks/prisma-cloud-go/pull/24
- Update go library and add jira to the config type validation: https://github.com/PaloAltoNetworks/terraform-provider-prismacloud/pull/107

## Steps to reproduce

1. Set `jira` as a config type
2. Run terraform plan

## Context

Jira is our finding tracking tool, we automatically assign tickets to teams through Prisma Cloud. To standardised our Prisma Cloud setup we use terraform and need the Jira integration to be able to have one module which can be reused for each team.

## Your Environment

- Version used: 1.2.1
- Operating System and version (desktop or mobile): Win 10

**Comment by hross-frae** [comment]
@trishala1999 are you able to have a look at this PR please and merge it. It is blocking our use of the terraform provider for Prisma Cloud

**Comment by trishala1999** [comment]
@hross-frae PR is merged in the new release v1.2.6. Please check.

**Comment by hross-frae** [comment]
@trishala1999, these changes work successfully
