### ISSUE TITLE
AWS SQS integration with additional IAM is not possible

### ISSUE THREAD

**Issue by n-schilling** [PaloAltoNetworks/terraform-provider-prismacloud#114]
## Describe the bug

If you want to use the resource "prismacloud_integration" to create an integration with AWS SQS, you can't configure additional IAM information like role ARN or external id. As per API documentation (1), you need to set the parameter "moreInfo=true", which is not available in the Terraform provider as per documentation (2) and per code.

(1) https://prisma.pan.dev/api/cloud/api-integration-config/#amazon-sqs
(2) https://registry.terraform.io/providers/PaloAltoNetworks/prismacloud/latest/docs/resources/integration

## Expected behavior

I can use the parameter "more_info" in the integration config to be able to configure additional IAM credentials via role_arn and external_id 

## Current behavior

It is not possible to deploy the following configuration:

`resource "prismacloud_integration" "sqs" {
    name = "Integration via AWS SQS"
    integration_type = "amazon_sqs"
    description = "Integration via AWS SQS"
    enabled = true
    integration_config {
        queue_url = var.integration_sqs_url
        role_arn = var.integration_iam_role_arn
        external_id = var.integration_iam_role_external_id
    }
}`

The error I receive is the following:

`Creating...
╷
│ Error: 400/https://api.eu.prismacloud.io/integration Error(msg:invalid_integration_type severity:error subject:invalid_param_value)
│ 
│   with prismacloud_integration.sqs,
│   on .terraform/fixed_integrations.tf line 1, in resource "prismacloud_integration" "sqs":
│    1: resource "prismacloud_integration" "sqs" {
`
or if I try to use "more_info", I receive the following message:

`│ Error: Unsupported argument
│ 
│   on .terraform/fixed_integrations.tf line 10, in resource "prismacloud_integration" "sqs":
│   10:         more_info = true
│ 
│ An argument named "more_info" is not expected here.`

## Possible solution

1) I can use "more_info" as part of the integration_config
2) The Terraform provider recognizes that role_arn and external_id are configured and sets the parameter "moreInfo" on its own in the API call

## Steps to reproduce

Configure the resource as mentioned above and try to apply the configuration

## Context

We need additional IAM credentials for the AWS SQS queue, and we can't configure the AWS SQS integration via Terraform.

## Your Environment

- Prisma Terraform Provider version: 1.2.2
- Terraform version: 1.1.5

**Comment by trishala1999** [comment]
This issue is fixed in v1.2.3
