### ISSUE TITLE
Please publish darwin_arm64 versions of your provider

### ISSUE THREAD

**Issue by gtmtech** [PaloAltoNetworks/terraform-provider-prismacloud#122]
## Describe the bug

Most of our teams use new mac M1s, and you have not published a darwin_arm64 version of your provider, so we get this trying to use it:

```
Provider registry.terraform.io/paloaltonetworks/prismacloud v1.1.10 does
│ not have a package available for your current platform, darwin_arm64.
```

Note that although this refers to 1.1.10 - the same is true of latest versions. 

Arm64 is the defacto standard of future mac operating systems, so it would be good to support this ASAP. 

Many thanks!

**Comment by trishala1999** [comment]
@gtmtech darwin_arm64 version is published in latest release v1.2.6. Please check.
