### ISSUE TITLE
Policies changing "savedSearch" from "true" to "null" every plan 

### ISSUE THREAD

**Issue by ryan-stavella** [PaloAltoNetworks/terraform-provider-prismacloud#125]
## Describe the bug

All of our policies are managed via TF and are not saved searches. When we go to plan it wants to change every policy "savedSearch" from "true" to "null" even thought they are not saved searches. This will occur on the next plan even if no changes are applied

## Expected behavior

Policies should not be updated in place when there are no changes made. They should remain as ""savedSearch" = "false".

## Current behavior

Every plan, all the policies are changing from "savedSearch" from "true" to "null". This leads to an enormous plan output that is hard to read.

## Screenshots

<img width="872" alt="Screen Shot 2022-03-31 at 12 55 13 PM" src="https://user-images.githubusercontent.com/71134114/162262328-446f17f9-2821-4638-b9cb-211041ce935b.png">

## Context

None of our policies are saved searches. All of a sudden it appears they are being recognized as saved searches with some sort of ID as the criteria field. It will apply without issue but we'll see the exact same changes the next plan. This is for every policy we manage via TF. These policies have been in code for 2 years without this issue

## Your Environment

AWS, latest version of TF provider

**Comment by trishala1999** [comment]
@ryan-stavella This issue fixed in v1.2.6 but also it's required to add `"savedSearch": false` or `"savedSearch": true` in tf resource block based on whether policy is using a RQL query or saved search id. Please refer https://registry.terraform.io/providers/PaloAltoNetworks/prismacloud/latest/docs/resources/policy

**Comment by ryan-stavella** [comment]
Confirmed 1.2.6 resolved out issue. Thanks!
