### ISSUE TITLE
Cannot unset prismacloud_policy.recommendation once set

### ISSUE THREAD

**Issue by andrew-sweet-db** [PaloAltoNetworks/terraform-provider-prismacloud#126]
## Describe the bug
Setting the recommendation attribute of a prisma_policy to a null or empty value after having set it to a non-null, non-empty value is not applied.

## Expected behavior
Setting the recommendation attribute of a prisma_policy to a null or empty value and applying that configuration should set the corresponding value in Prisma Cloud.

## Current behavior
The recommendation value does not get updated.

## Possible solution
Optional fields in https://github.com/PaloAltoNetworks/prisma-cloud-go/blob/c526475c8f63923fbdbb397d1c42aa1e70104b8a/policy/structs.go#L13 are marked with 'omitempty'. I _think_ this means you cannot set the fields to null or empty string.

## Steps to reproduce
1. Define a prismacloud_policy resource with the "recommendation" attribute set to a non-null, non-empty value.
1. Apply the config.
1. Update the "recommendation" attribute to null or the empty string.
1. Re-apply the config. You'll see the update in the plan e.g. `recommendation = "Fix it!" -> null`.
1. Check the policy in the Prisma Cloud UI. The recommendation will still have a non-null, non-empty value.
1. Re-plan the config. The same action will be proposed as in step 4.

## Context
* We're providing incorrect policy recommendation information to Alert recipients, causing toil and frustration.
* This issue causes noise in every plan we perform creating uncertainty regarding the scope of releases.

## Your Environment
Reproduced on Ubuntu 20.04 using v1.1.5 and v1.2.3 of the Prisma Cloud Terraform Provider using Terraform v0.14.10.

**Comment by trishala1999** [comment]
@andrew-sweet-db This issue is fixed in v1.2.6. Please check
