### ISSUE TITLE
Error: The terraform-provider-prismacloud_v1.2.3 plugin crashed!

### ISSUE THREAD

**Issue by jasonckeating** [PaloAltoNetworks/terraform-provider-prismacloud#127]
## Describe the bug

Terraform plan started failing due to provider error.

## Current behavior

Plan crashes.

## Steps to reproduce

1. Run a Terraform plan

```
Stack trace from the terraform-provider-prismacloud_v1.2.3 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf528a8]

goroutine 46 [running]:
github.com/terraform-providers/terraform-provider-prismacloud/prismacloud.saveIntegration(0xc000445880, 0xc000a56360, 0x24, 0xc000a88d40, 0x1a, 0xc000a87f50, 0xa, 0xc0005b9680, 0x5e, 0x0, ...)
	github.com/terraform-providers/terraform-provider-prismacloud/prismacloud/resource_integration.go:483 +0x438
github.com/terraform-providers/terraform-provider-prismacloud/prismacloud.readIntegration(0xc000445880, 0x114fb80, 0xc0001c1110, 0xc000445880, 0x0)
	github.com/terraform-providers/terraform-provider-prismacloud/prismacloud/resource_integration.go:711 +0x2d5
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0001baf00, 0xc00072cc80, 0x114fb80, 0xc0001c1110, 0xc00028ef50, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/resource.go:470 +0x119
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc00028e890, 0x154d520, 0xc00043e840, 0xc000110cc0, 0xc00028e890, 0x0, 0xc0002f4ba0)
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/helper/plugin/grpc_provider.go:535 +0x3d8
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0x11cfe60, 0xc00028e890, 0x154d520, 0xc00043e840, 0xc000110c60, 0x0, 0x154d520, 0xc00043e840, 0xc0003de400, 0x3f6)
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/tfplugin5/tfplugin5.pb.go:3269 +0x217
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003476c0, 0x155a560, 0xc000407680, 0xc000294c00, 0xc0005ec9f0, 0x1d7dbb0, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1194 +0x50a
google.golang.org/grpc.(*Server).handleStream(0xc0003476c0, 0x155a560, 0xc000407680, 0xc000294c00, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1517 +0xcfd
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0000aa550, 0xc0003476c0, 0x155a560, 0xc000407680, 0xc000294c00)
	google.golang.org/grpc@v1.32.0/server.go:859 +0xa1
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.32.0/server.go:857 +0x204

Error: The terraform-provider-prismacloud_v1.2.3 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

## Context

Cannot manage PrismaCloud with Terraform.

## Your Environment

- Version used: 1.2.3
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3):
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by n-schilling** [comment]
We have the same challenge, blocking us entirely.

Terraform v1.1.9
on darwin_amd64
provider registry.terraform.io/paloaltonetworks/prismacloud v1.2.3 

(as well as with Terraform v.1.1.8)

**Comment by trishala1999** [comment]
@jasonckeating @n-schilling We tried to reproduce this issue from our end with `Terraform v1.1.9` and provider `registry.terraform.io/paloaltonetworks/prismacloud v1.2.3` on `darwin_amd64` but we are not able to reproduce. Everything is working fine for us. Please check again and still if you find the issue give us the detailed information for reproducing the same.

**Comment by n-schilling** [comment]
> @jasonckeating @n-schilling We tried to reproduce this issue from our end with `Terraform v1.1.9` and provider `registry.terraform.io/paloaltonetworks/prismacloud v1.2.3` on `darwin_amd64` but we are not able to reproduce. Everything is working fine for us. Please check again and still if you find the issue give us the detailed information for reproducing the same.

Can you give me a hint on which information can be helpful for you to investigate further? I'm working on a Mac 12.3.1. 

As part of my tests, I deleted the whole ".terraform" folder in my project to have a clean start. The stack trace I'm receiving is exactly as posted by @jasonckeating. Do you see potential issues in the code mentioned in the stack trace which could lead to a null pointer? Effectively I did not change something in my codebase.

**Comment by jasonckeating** [comment]
@trishala1999 thanks for digging in.

Same as @n-schilling, no changes to Terraform.
Tested again this morning, I'm getting the documented error on:
- TFE Enterprise
- Macbook Pro (Monterrey 12.3.1)

**Comment by trishala1999** [comment]
@jasonckeating @n-schilling Can you please once confirm if this issue is occurring only with `v1.2.3` or with previous version also.

**Comment by n-schilling** [comment]
@trishala1999 Unfortunately, I can't easily roll back my code to test previous versions. It definitely occurs with `v1.2.3`.

**Comment by jasonckeating** [comment]
tested with `v1.2.2` and `v1.2.1` (different error)
```
│ Error: unexpected end of JSON input
│ 
│   with prismacloud_integration.xxx,
│   on integrations.tf line 21, in resource "prismacloud_integration" "xxx":
│   21: resource "prismacloud_integration" "xxx" {
```

**Comment by trishala1999** [comment]
Have raised [this PR](https://github.com/PaloAltoNetworks/terraform-provider-prismacloud/pull/130) to fix this issue. Will get this merged soon.

**Comment by iokush** [comment]
@trishala1999 Could we get an estimate by when the fix will be merged? Unfortunately, we're completely blocked as well.

**Comment by trishala1999** [comment]
@iokush Sorry for inconvenience, we will get this merged by tomorrow EOD and push the new release.
