### ISSUE TITLE
prismacloud_cloud_account detects diff on every terraform plan for an Azure subscription

### ISSUE THREAD

**Issue by ZachTB123** [PaloAltoNetworks/terraform-provider-prismacloud#13]
## Describe the bug

Every `terraform plan` for an Azure subscription detects a diff:

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

# prismacloud_cloud_account.account will be updated in-place
~ resource prismacloud_cloud_account account {
    ~ azure {
        ...
        ~ key = (sensitive value)
        ...
    }
}
```

## Expected behavior

There should be no resources to create or update since nothing has changed.

## Current behavior

`terraform plan` detects a diff and `terraform apply` modifies the resource.

## Possible solution

Looking at the state file, the reason for this is because `key` is being masked:

```json
...
"key": "******************"
...
```

This is causing the diff.

## Steps to reproduce

1. Create a `prismacloud_cloud_account` resource for an Azure subscription.
2. Do a `terraform plan` and `terraform apply`. The account is now onboarded.
3. Do not make any changes to the Terraform resource and run a `terraform plan`. A diff was detected.

## Your Environment

- Version used: 1.0.8

**Comment by ebeuerle** [comment]
Is this still an issue?

**Comment by ZachTB123** [comment]
@ebeuerle Yes, this is still an issue.

**Comment by trv-msieczko** [comment]
I'm experiencing this with Google Cloud as well

```
  ~ resource "prismacloud_cloud_account" "gcp_project" {
        id                 = "gcp:projectName"
        # (1 unchanged attribute hidden)

      ~ gcp {
          ~ credentials_json         = (sensitive value)
            name                     = "projectName"
            # (8 unchanged attributes hidden)
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

**Comment by shinmog** [comment]
The issue here is that the Prisma Cloud API returns a bunch of asterisks instead of the configured value.  This happens for:

* `key` for Azure cloud accounts
* `PrivateKey` for GCP cloud accounts (found within the `credentials_json` param

Will be suppressing the diff detection so that the provider doesn't complain all the time, but a true fix will require some sort of API change that is beyond the scope of the provider.
