### ISSUE TITLE
Allow prismacloud_cloud_account to disable the account on terraform destroy

### ISSUE THREAD

**Issue by ZachTB123** [PaloAltoNetworks/terraform-provider-prismacloud#14]
### Is your feature request related to a problem?

We have a requirement that we disable rather than delete a cloud account when we go through our decommission process. We do this to ensure we do not lose the history for the account. Currently we are using a custom script to onboard cloud accounts in Prisma but would like to switch to using the Terraform provider. With our current script, we accomplish the disable using the `Patch Cloud Account` request with a request body of:

```json
{
    "enabled": false
}
```

Our current decommission process calls `terraform destroy`, which is going to break the requirement we have since it looks like the `prismacloud_cloud_account` resource calls [delete on destroy](https://github.com/PaloAltoNetworks/terraform-provider-prismacloud/blob/master/prismacloud/resource_cloud_account.go#L19). The `prismacloud_cloud_account` resource does have an `enabled` field but like I previously mentioned, we call `terraform destroy` during our decommission process.

### Describe the solution you'd like

I would like to see some sort of configuration exposed, e.g. at the provider level:

```
provider prismacloud {
    ...
    cloud_account_action_on_destroy = "disable"
    ...
}
```

or at the resource level:

```
resource prismacloud_cloud_account account {
    destroy_action = "disable"
}
```

that allows me to configure the action that is taken when `prismacloud_cloud_account` is destroyed.

**Comment by zimmermanc** [comment]
@ZachTB123 I was told you implemented this on your side already. Would you be able to submit a Pull request for your changes?

**Comment by ZachTB123** [comment]
@zimmermanc I can though it might be a bit yet since I have to go through an internal process first.

**Comment by ebeuerle** [comment]
Fixed in next push.

**Comment by ebeuerle** [comment]
Should be fixed now.
