### ISSUE TITLE
Add resource for RQL (saved searches)

### ISSUE THREAD

**Issue by sekido** [PaloAltoNetworks/terraform-provider-prismacloud#15]
### Is your feature request related to a problem?

I'm happy if the provider can manage RQL (saved searches) with Terraform to track history why I update it.

Policies are tracking resources on clouds, and RQL (saved searches) are required by Policies. Currently, Terraform Provider Prisma Cloud has a resource for policies. Still, I have to pass the ID to create saved searches outside Terraform -- on the web console.

### Describe the solution you'd like

We would like to have a new resource for RQL or saved searches.
I guess, at least, it has name and query as input and id as output.

```terraform
resource "prismacloud_rql" "resouces_with_global_ipaddr" {
    name = "List resources with global IP adddress"
    query = "config from cloud.resource where ..."
}

resource "prismacloud_policy" "example" {
    name = "My Policy"
    policy_type = "network"
    rule {
        name = "my rule"
        # now We can refer it with expected RQL
        criteria = prismacloud_rql.resouces_with_global_ipaddr.id
        parameters = {
            "savedSearch": "true",
            "withIac": "false",
        }
        rule_type = "Config"
    }
}
```

**Comment by ghost** [comment]
I would also be keen to see this feature implemented as the terraform provider currently lacks the support to create and manage the saved searches used with policies.

**Comment by sbldevnet** [comment]
This feature would be great for versioning policies and change management easily.
I need it!

**Comment by ebeuerle** [comment]
v1.1.0 has been released and supports this now.  CAVEAT: network saved searches is not in place yet but will be next week.
