### ISSUE TITLE
role_type "Developer" missing in resource "user_role"

### ISSUE THREAD

**Issue by aymericpineau** [PaloAltoNetworks/terraform-provider-prismacloud#158]
PrismaCloud v1.2.9

Hi, the resource "**prismacloud_user_role**" allows to choose the "**role_type**".
However, the "**role_type**" parameter is missing the "**Developer**" role

Here is the Terraform Error raised when trying to create a "**role_type = Developer**" role
**Error: expected role_type to be one of [System Admin Account Group Admin Account Group Read Only Cloud Provisioning Admin Account and Cloud Provisioning Admin Build and Deploy Security], got Developer**

Cheers,
Aymeric PINEAU

**Comment by landro** [comment]
We need this too! Also see: https://github.com/PaloAltoNetworks/terraform-provider-prismacloud/pull/160

**Comment by landro** [comment]
#160 was merged. This issue can be closed.

**Comment by trishala1999** [comment]
Issue is fixed in version 1.2.10
