### ISSUE TITLE
Allow prismacloud_cloud_account to update the account on create

### ISSUE THREAD

**Issue by ZachTB123** [PaloAltoNetworks/terraform-provider-prismacloud#16]
### Is your feature request related to a problem?

If an account is already onboarded at the time of creating the `prismacloud_cloud_account` resource, it will fail and say that it must be imported. I would like to see a feature that allows you to configure this resource in such a way that it will not fail in this scenario, and instead update the account.

### Describe the solution you'd like

The resource ends up looking like:

```
resource prismacloud_cloud_account account {
    update_on_create = true

    ...
}
```

### Additional context

I ended up forking the provider and implementing this the way I described above and it works.

**Comment by erikpaasonen** [comment]
ZachTB123's changes to his fork can be previewed here: https://github.com/PaloAltoNetworks/terraform-provider-prismacloud/compare/master...ZachTB123:dev

**Comment by zimmermanc** [comment]
@ZachTB123 Would you be able to add this as Pull request for us to review?

**Comment by ebeuerle** [comment]
Fixed in next push.

**Comment by ebeuerle** [comment]
Should be fixed. Closing.
