### ISSUE TITLE
Allow option to add Custom permission groups to User Roles in Terraform

### ISSUE THREAD

**Issue by GilesF9** [PaloAltoNetworks/terraform-provider-prismacloud#168]
### Describe the solution you'd like
We have built the Permission Groups via the GUI but would like to be able to allocate them to the user role through Terraform. We would also like to be able to create the Permission Group itself via Terraform however we will raise this under a separate request.

(https://registry.terraform.io/providers/PaloAltoNetworks/prismacloud/latest/docs/resources/user_role)

Example of the desired code:
resource "prismacloud_user_role" "example" {
    name = "my user role"
    description = "Made by Terraform"
    role_type = "Custom Permission Group " #This is not currently possible
}

**Comment by nikitapanw** [comment]
@GilesF9 Thanks for reporting the issue. This has been fixed. Closing the issue.
