### ISSUE TITLE
Ability to create custom Permission Groups in Terraform

### ISSUE THREAD

**Issue by GilesF9** [PaloAltoNetworks/terraform-provider-prismacloud#169]
### Describe the solution you'd like
We are moving towards a management model where all Prisma Cloud configuration changes are made via Terraform. Currently we are not able to build the new custom Permission Groups using Terraform.

**Comment by ruzickap** [comment]
Looks like this one is the same as https://github.com/PaloAltoNetworks/terraform-provider-prismacloud/issues/170.

**Comment by ftbrecordspan** [comment]
Permission Groups are now supported under [v1.3.3](https://github.com/PaloAltoNetworks/terraform-provider-prismacloud/releases/tag/v1.3.3).
