### ISSUE TITLE
Cannot use this provider with "Anomaly" type policies

### ISSUE THREAD

**Issue by ryan-stavella** [PaloAltoNetworks/terraform-provider-prismacloud#17]
## Describe the bug

Cannot put the Anomaly policies into code as they are not supported.

## Expected behavior

Policy type should have support for Config, Audit, Network, and Anomaly policies

## Current behavior

Anomaly type is recognized after importing but cannot be used

![tfss](https://user-images.githubusercontent.com/71134114/105552435-e7b12a80-5cd1-11eb-97ce-0c5d9359cf5c.png)

Trying to backport an Anomaly policy leads to this error:

`Error: expected policy_type to be one of [config audit_event network], got anomaly
`

## Possible solution

Add policy.PolicyTypeAnomaly to the supported policy types
```
			"policy_type": {
				Type:        schema.TypeString,
				Required:    true,
				Description: "Policy type",
				ValidateFunc: validation.StringInSlice(
					[]string{
						policy.PolicyTypeConfig,
						policy.PolicyTypeAuditEvent,
						policy.PolicyTypeNetwork,
					}
```

## Steps to reproduce

1. Import an existing Anomaly policy
2. Run a TF Plan 

## Context

We backport all prisma policies to code so that they can be managed easily. This allows us to tag and organize with custom compliance tags.

**Comment by ebeuerle** [comment]
Hi Ryan,
We didn't add support for anomaly policies because you can't create them in the system unlike config/network/audit policies.  What capabilities do you need for anomaly policies?  Ability to add compliance standards to them?

**Comment by ryan-stavella** [comment]
Yes, we need the ability to add them to alert rules, add tags and compliance standards.

**Comment by ebeuerle** [comment]
Okay thanks - I will put this in our backlog to get done.  Thanks for the info!

**Comment by jeremyp-synopsys** [comment]
+1

This is blocking us from fully managing our custom compliance standards that would leverage the anomaly policies...

**Comment by ryan-stavella** [comment]
> Okay thanks - I will put this in our backlog to get done. Thanks for the info!

Hi @ebeuerle, Is it possible to add support for Build policies too? We would like to manage custom IaC policies and also add custom compliance tags + standards like mentioned for the Anomaly policies.

**Comment by ebeuerle** [comment]
Fixed.
