### ISSUE TITLE
Missing managing Notifications templates feature

### ISSUE THREAD

**Issue by MrImpossibru** [PaloAltoNetworks/terraform-provider-prismacloud#171]
Hello,

There's an API to manage them but I see that feature is missing in the Terraform Provider.
https://prisma.pan.dev/api/cloud/cspm/notification-templates

**Comment by AnushreeHS** [comment]
@MrImpossibru Thanks for opening the issue, this is released with terraform version = "1.3.8"
Closing the issue
Thanks
