### ISSUE TITLE
No logic for deleting enterprise settings

### ISSUE THREAD

**Issue by infosec-shinobi** [PaloAltoNetworks/terraform-provider-prismacloud#180]
https://github.com/PaloAltoNetworks/terraform-provider-prismacloud/blob/6844cf65d574d0fc522b128074ac5205c691d8df/prismacloud/resource_enterprise_settings.go#L128

this function simply returns nil... There is no logic to actually remove these settings.

**Comment by infosec-shinobi** [comment]
Is this due to not having a destroy endpoint (https://prisma.pan.dev/api/cloud/cspm/settings#operation/update-enterprise-settings)? Assuming you can't delete the actual settings because they have to exist? If you delete, should the settings just all return to default?

**Comment by nikitapanw** [comment]
@infosec-shinobi enterprise settings don't have destroy endpoint, you can just edit the settings.
Closing the issue, feel free to reopen
Thank you
