### ISSUE TITLE
Add Trusted IP Address as a resource

### ISSUE THREAD

**Issue by john-lowry** [PaloAltoNetworks/terraform-provider-prismacloud#183]
### Is your feature request related to a problem?

Trying to capture everything in terraform, but adding Trust IP addresses for alerts and logins with PRisma has to be done via the console.

### Describe the solution you'd like

Adding trust ip addresses, both for alert as well as for login as a resource in the provider

**Comment by nikitapanw** [comment]
@john-lowry We have added support for Trusted IP Address from terraform, you can use it in latest version of terraform provider v1.3.7.
Closing this issue, feel free to reopen
