### ISSUE TITLE
Cannot create a Slack integration

### ISSUE THREAD

**Issue by Melchizedech** [PaloAltoNetworks/terraform-provider-prismacloud#2]
## Describe the bug

It is not possible to create a Slack integration. 

## Expected behavior

As outlined in the documentation, https://www.terraform.io/docs/providers/prismacloud/r/integration.html, I can add a Slack Integration.

## Current behavior

When I add a Slack integration using this config 

```
resource "prismacloud_integration" "slack" {
  name             = "Slack"
  integration_type = "slack"
  description      = "Alert channel"
  enabled          = true

  integration_config {

    url = "your.url"
  }
}
```

I get the error : 

```
Error: 400/https://api2.eu.prismacloud.io/integration Error(msg:invalid_slack_webhook_url severity:error subject:invalid_param_value)
```

When I use the right param as expected in your API

```
resource "prismacloud_integration" "slack" {
  name             = "Slack"
  integration_type = "slack"
  description      = "Alert channel"
  enabled          = true

  integration_config {

    webhook_url = "your.url"
  }
}
```
I get the error : 

```
Error: Unsupported argument

  on integrations.tf line 9, in resource "prismacloud_integration" "slack":
   9:     webhook_url = "your.url"
```

## Possible solution

Allow the `webhook_url` at least in the type a Slack integration is meant ?
https://github.com/terraform-providers/terraform-provider-prismacloud/blob/master/prismacloud/resource_integration.go

## Steps to reproduce

1. using this resource
```
resource "prismacloud_integration" "slack" {
  name             = "Slack"
  integration_type = "slack"
  description      = "Alert channel"
  enabled          = true

  integration_config {
    # #security-alerts
    webhook_url = "your.url"
  }
}
```
2. or this resource
```
resource "prismacloud_integration" "slack" {
  name             = "Slack"
  integration_type = "slack"
  description      = "Alert channel"
  enabled          = true

  integration_config {
    # #security-alerts
    url = "your.url"
  }
}
```

3. applying this configuration will fail

## Context

I want to setup my alerting via terraform using Slack and i can't.
Using the API it works just fine.

## Your Environment

- Version used: 1.0.0
- go 1.13, terraform v0.12.28
- Linux XXX 5.7.9-arch1-1 PaloAltoNetworks/terraform-provider-prismacloud-orig#1 SMP PREEMPT Thu, 16 Jul 2020 19:34:49 +0000 x86_64 GNU/Linux

**Comment by ebeuerle** [comment]
Fixed.

**Comment by jasonckeating** [comment]
I am getting the exact issue described here.

Version: 1.1.2
Requesting a reopen
