### ISSUE TITLE
Support for Enterprise Settings Audit Logs

### ISSUE THREAD

**Issue by mtobias-getty** [PaloAltoNetworks/terraform-provider-prismacloud#209]
### Is your feature request related to a problem?

Terraform provider is lagging behind the available features of the `Settings` API.  Prisma Cloud supports the sending of console audit logs to an integration, describe on the https://pan.dev/prisma-cloud/api/cspm/update-enterprise-settings/ API page.  It does not appear that the Terraform provider currently supports this setting.  https://registry.terraform.io/providers/PaloAltoNetworks/prismacloud/latest/docs/data-sources/enterprise_settings

### Describe the solution you'd like

Include support for the sending of audit logs to a Prisma integration via the Terraform provider.

### Describe alternatives you've considered

Enabling this setting by hand in the console since the Terraform provider does not support this option.

### Additional context

N/A

**Comment by nikitapanw** [comment]
@mtobias-getty Thanks for opening the issue, this is released with terraform version = "1.3.4"
Closing the issue
Thanks
