### ISSUE TITLE
Inconsistent api on prismacloud_cloud_account_v2

### ISSUE THREAD

**Issue by andersro93** [PaloAltoNetworks/terraform-provider-prismacloud#233]
## Describe the bug
Inconsistent api for Features block in the prismacloud_cloud_account_v2 resource. See screenshot for details.

## Expected behavior
No change

## Current behavior
Diff with different name on feature

## Screenshots
![image](https://github.com/PaloAltoNetworks/terraform-provider-prismacloud/assets/6398527/9e639efd-ae81-4832-a8fc-cf4a6bb36fe4)

## Context
We experience this issue for all Azure subscriptions we try to provision in Prisma Cloud

## Your Environment
Terraform Cloud with provider version 1.4.1 of prismacloud provider.

**Comment by ftbrecordspan** [comment]
This is fixed under v1.4.2.
