### ISSUE TITLE
No policy validation when provisioning Prisma cloud policy, resulting in the state file being modified even though the API returns a bad request

### ISSUE THREAD

**Issue by imroot01** [PaloAltoNetworks/terraform-provider-prismacloud#234]
## Current behavior

We are using our Prisma Cloud Terraform Provider to create some custom policies. https://registry.terraform.io/providers/PaloAltoNetworks/prismacloud/latest/docs

There appears to be no policy validation when provisioning Prisma cloud policy, resulting in the state file being modified even though the API returns a bad request (please see attached). Is there an existing fix for this? 
![image](https://github.com/PaloAltoNetworks/terraform-provider-prismacloud/assets/38302424/df5a22aa-26d3-4270-acba-5e7e3582de14)

Also when writing RQL in VSC -;RQL files have to be single line otherwise it will return 400 errors (please see attached). Is this expected behaviour? 
![image](https://github.com/PaloAltoNetworks/terraform-provider-prismacloud/assets/38302424/dcaf71cc-7476-4fa5-93a0-e93da480594d)

## Steps to reproduce

See attached

1.
2.
4.
5.

## Screenshots
![image](https://github.com/PaloAltoNetworks/terraform-provider-prismacloud/assets/38302424/aaf6dbc1-e163-4b6f-aff3-b624121ac6b2)

## Your Environment

- Version used:
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3):
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by AnushreeHS** [comment]
@imroot01 We are unable to reproduce the error, could you please give us more information?

**Comment by AnushreeHS** [comment]
@imroot01 Closing the issue, feel free to reopen it if you encounter the same problem again.
