### ISSUE TITLE
"prismacloud_permission_group" resource has a bug with "ComputeAccessUI" feature

### ISSUE THREAD

**Issue by dkrose1999** [PaloAltoNetworks/terraform-provider-prismacloud#241]
## Describe the bug

While creating "prismacloud_permission_group" resource, I have an issue with the following feature: "ComputeAccessUI".  If I set update=true as an operation, then I get Error:400

## Expected behavior

When I set update=true, the resource should create.  To test the API, I confirmed I can set this feature to update in the admin web console with no issues. This is what's labeled as "Host Vulnerabilities & Compliance Policies" and located in Compute:Monitor area.

## Current behavior

I get an error with 400 status code when trying to create the resource.

## Steps to reproduce

1. create a permission group while including the following snippet of code
features {
    feature_name = "computeAccessUI"
   operations {
           update = true
           }
}
2. try to run a plan/apply (the plan will run, but apply will not)

## Screenshots

https://github.com/dkrose1999/PrismaScreenshot/blob/main/image001.png

## Context

I can automate 95 out of 96 features in this permission group, but not this one.

**Comment by AnushreeHS** [comment]
@dkrose1999 Thanks for opening the issue, ComputeAccessUI provides UI access.  This feature is automatically added if another compute feature is selected. You do not need to send this feature explicitly in the terraform block. Hope this resolves your query. If you still have any queries feel free to reach out.
Thanks

**Comment by dkrose1999** [comment]
Why was this issue closed?  You stated the feature is automatically added if another compute feature is selected.  What other feature is that?  You also stated I don't need to define this in terraform block.  Then please tell me how am I supposed to set the following feature accessible via the web GUI: "Compute/Monitor/Host Vulnerabilities & Compliance Policies"
