### ISSUE TITLE
Exceptions management 

### ISSUE THREAD

**Issue by Danny-Cooke** [PaloAltoNetworks/terraform-provider-prismacloud#245]
### Is your feature request related to a problem?

Exceptions management 

### Describe the solution you'd like

I would like to be able to manage : -
collections
tag
CVE's
Relating to container scanning in prisma cloud. We have a pipeline that runs the image builds / scans and it is preferable to manage the exceptions process from git rather than logging into the UI and so terraform would be a great option.

### Describe alternatives you've considered

Using the UI but developers dont want to use UI's 

### Additional context

Developers find it adds too much time onto their development logging into the UI and clicking through screens / tabs repetitively and so feel this would be a huge improvement to the current process

**Comment by ftbrecordspan** [comment]
This is an entirely reasonable feature request, but one which falls outside of the scope of the current capabilities of this provider. The [Prisma Cloud Compute Terraform Provider](https://github.com/PaloAltoNetworks/terraform-provider-prismacloudcompute) would be better aligned with this problem space so please raise this request there.
