### ISSUE TITLE
'prismacloud_cloud_account_v2' Azure Error: Insufficient features blocks

### ISSUE THREAD

**Issue by erikpaasonen** [PaloAltoNetworks/terraform-provider-prismacloud#247]
## Describe the bug

```
╷
│ Error: Insufficient features blocks
│
│   on <empty> line 0:
│   (source code not available)
│
│ At least 1 "features" blocks are required.
╵
```

## Expected behavior

Should be able to run `terraform apply` without error, and it should create a cloud account in Prisma Cloud console.

## Current behavior

plan and apply both fail with the error quoted above.

## Steps to reproduce

Terraform file contents to reproduce:
```hcl
data "azurerm_client_config" "current" {}

resource "prismacloud_cloud_account_v2" "account" {
  disable_on_destroy = false
  azure {
    client_id            = local.client_id
    account_id           = var.account_id
    account_type         = "account"
    enabled              = true
    name                 = "test azure account"
    group_ids            = [var.known_good_group_guid]
    key                  = local.key
    monitor_flow_logs    = true
    service_principal_id = local.service_principal_id
    tenant_id            = data.azurerm_client_config.current.tenant_id
    features {
      name  = "Agentless Scanning"
      state = "enabled"
    }
  }
}

```

1. `terraform init -upgrade`
2. `terraform plan` (or `terraform apply`)

## Context

We currently use `prismacloud_cloud_account` to configure Azure subscriptions into Prisma Cloud. Exploring changing this to `prismacloud_cloud_account_v2`.

I went line by line down the documentation for `prismacloud_cloud_account_v2` in the Azure section and made sure everything that is required is present. The documentation is not super clear as to the definition of `features`, but the example laid out in the documentation indicates it is an HCL "block" that should reside within the `azure` block. I get a different error if I try e.g. to move `features {}` outside of the `azure` block into the resource itself.

## Your Environment

- Version used: 
> Initializing provider plugins...
> \- Finding latest version of hashicorp/azurerm...
> \- Finding latest version of paloaltonetworks/prismacloud...
> \- Finding hashicorp/aws versions matching ">= 3.0.0"...
> \- Finding latest version of hashicorp/azuread...
> \- Using previously-installed hashicorp/aws v5.8.0
> \- Using previously-installed hashicorp/azuread v2.40.0
> \- Using previously-installed hashicorp/azurerm v3.65.0
> \- Using previously-installed paloaltonetworks/prismacloud v1.4.5

- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3):  Terraform v1.5.0
- Operating System and version (desktop or mobile): MacOS Ventura on Intel CPU

**Comment by erikpaasonen** [comment]
never seen this in any other provider before:
```
│   on <empty> line 0:
│   (source code not available)
```
makes it difficult to track down the error.

I isolated the problem in a new dir with bare-minimum config and traced it to the `prismacloud_cloud_account_v2` resource with an `azure {}` block.

**Comment by erikpaasonen** [comment]
still occurs even if the `features {}` block is copied and pasted from [the documentation example for Azure](https://registry.terraform.io/providers/PaloAltoNetworks/prismacloud/latest/docs/resources/cloud_account_v2#example-usage-3-azure-cloud-account-onboarding).

**Comment by AnushreeHS** [comment]
@erikpaasonen Thanks for opening the issue, I took the time to investigate and replicate the problem you reported. After thorough testing, I can confirm that the error you encountered is not caused by "prismacloud_cloud_account_v2," as initially presumed. Instead, it seems to be related to the data "azurerm_client_config”. If you still have any queries feel free to reach out.

**Comment by erikpaasonen** [comment]
confirmed! thank you for investigating!
