### ISSUE TITLE
can we create both Run and Build policy using `prismacloud_policy` resource

### ISSUE THREAD

**Issue by EkhatorOwen** [PaloAltoNetworks/terraform-provider-prismacloud#255]
### Is your feature request related to a problem?
In the PrismaCloud UI, we can create both `Run` and `Build` policies as seen in the screenshot attached. is there a way to do so using the `prismacloud_policy` resource. Using that resource, i noticed that it only allows for one `rule` block which leads me to believe you cannon have both "Run" and "Build" policy in one resource.

### Describe the solution you'd like

it would be nice if we could create both build and run policy subtype using the `prismacloud_policy` resource.

### Additional context

![Screenshot 2023-09-05 at 11 58 30 AM](https://github.com/PaloAltoNetworks/terraform-provider-prismacloud/assets/31750505/a473ea0f-1d57-4d35-98c7-e15f132621dd)

Screenshot showing the ability to check (and create) both Build and Run policy subtype in one policy.

**Comment by AnushreeHS** [comment]
@EkhatorOwen Thanks for opening the issue, this is released with terraform version = "1.4.9"
