### ISSUE TITLE
Policies/ Saved Searches cannot be Terraform Managed

### ISSUE THREAD

**Issue by jasonckeating** [PaloAltoNetworks/terraform-provider-prismacloud#27]
## Describe the bug

To create a policy via Terraform, 3 resources have to be defined:
- prismacloud_rql_search
- prismacloud_saved_search
- prismacloud_policy

A `prismacloud_saved_search` cannot be updated. 
For example, if the name of the search is updated, the Terraform fails to apply because the search name already exists. 

When running `terraform apply` with an update to RQL, the provider attempts to create `prismacloud_saved_search` although it exists in terraform state AND in Prisma Cloud.

This is a serious problem that `prismacloud_saved_search` is neither updated or destroyed, because if RQL is updated and Terraform applied, it tries to create `prismacloud_saved_search` and fails on the because it sees the existing saved search.

## Expected behavior

Resources should handle basic updates, so Terraform applies do not fail after small variable changes.
`prismacloud_saved_search` should handle updates and destroys, so a small change doesn't prevent a Terraform apply.

## Current behavior

When a change is made to the RQL of a search, the `prismacloud_saved_search` throws this error:
```
│ Error: 400/https://api3.prismacloud.io/search/history/01ce975e-c452-4ac5-ac01-fff6d7f956c8 Error(msg:duplicate_search_name severity:error subject:test terraform policy)
│ 
│   on .terraform/modules/prisma-policy/main.tf line 14, in resource "prismacloud_saved_search" "this":
│   14: resource "prismacloud_saved_search" "this" {
│ 
```

## Possible solution

Handle an update of RQL for a saved search.

## Steps to reproduce

1. Create these 3 resources:
- prismacloud_rql_search
- prismacloud_saved_search
- prismacloud_policy
2. Terraform Apply 
3. Modify the RQL
4. Terraform Apply

## Screenshots
![Screen Shot or saved_search failing](https://user-images.githubusercontent.com/18508669/115464237-66930200-a1f2-11eb-8520-aaa2b2d86e92.png)

## Context
This is breaking the ability to manage policies and saved searches with Terraform.

## Your Environment

- Version used:
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3):
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by ebeuerle** [comment]
Yes, this is a known issue and you need to modify the name of the saved search.  The API doesn't support deleting saved searches so we added this to the docs: "NOTE: Prisma Cloud does not currently support deleting RQL searches, so terraform destroy is a noop."

**Comment by jasonckeating** [comment]
Got it, I missed that statement in the docs.
To get around the issue for the time being, we've appended a random_id to the saved_search name. I'm just concerned about the list of saved_searches in Prisma growing very large over time.

**Comment by ebeuerle** [comment]
I will have to leave that up to our API/Product personnel to deal with...
