### ISSUE TITLE
Error: 404 error without the "X-Redlock-Status" header - returned HTML: (blank)

### ISSUE THREAD

**Issue by erikpaasonen** [PaloAltoNetworks/terraform-provider-prismacloud#272]
## Describe the bug

Certain `prismacloud_cloud_account_v2` resources now throwing this error after previously succeeding:
> Error running terraform plan
> with prismacloud_cloud_account_v2.account[0],
> on prismacloud.tf line 10, in resource "prismacloud_cloud_account_v2" "account":
> Error: 404 error without the "X-Redlock-Status" header - returned HTML:

(The absence of any actual HTML code seems to indicate the body of the 404 was empty.)

## Expected behavior

Terraform should plan and apply without error. If the cloud account has been deleted outside of Terraform, then Terraform should recognize that the resource needs to be recreated and recreate it.

## Current behavior

The Terraform plan errors out with the error message given above.

## Possible solution

- Detect cloud accounts in the Prisma Cloud tenancy which are no longer configured, and cause the Terraform resource to be "tainted" (or otherwise deleted+recreated).
- Add a body to >399 error pages to help pass-through some more context to the error message that winds up in Terraform as to what exactly went wrong.

## Steps to reproduce

1. create `prismacloud_cloud_account_v2` resource
2. run `terraform apply`
3. confirm account is successfully enrolled in Prisma Cloud console
4. delete the account from the Prisma Cloud console
5. rerun `terraform plan`

## Context

Terraform is designed as a declarative tool, meaning every time Terraform runs (successfully) it should result in the state of the managed environment matching what is defined in code. In this case, changes made outside of Terraform (i.e. deleting the cloud account via the Console) are not being detected as the resource having been deleted, but instead an error is being reported back through to the user. Seems as if this error should be caught and cause the `prismacloud_cloud_account_v2` resource to consider itself deleted from the Prisma Cloud tenancy, and re-create (i.e. "taint").

Tangentially related (in the sense they describe a similar "we'll pass-thru an HTTP status code and give you the HTML content which is empty" error pattern):
- #200
- #223

## Your Environment

- Version used: `prismacloud` provider v1.5.0 (originally confirmed on 1.3.7), Terraform v1.6.3
- Operating System and version (desktop or mobile): linux_amd64

**Comment by erikpaasonen** [comment]
confirmed that this issue still occurs with `prismacloud` provider v1.5.0. edited the OP to reflect.

**Comment by AnushreeHS** [comment]
@erikpaasonen Thanks for opening the issue, a fix has been released with terraform version = "1.5.5"
Closing the issue
Thanks
