### ISSUE TITLE
Support policySubTypes in data source `prismacloud_policies`

### ISSUE THREAD

**Issue by jgrumboe** [PaloAltoNetworks/terraform-provider-prismacloud#281]
### Is your feature request related to a problem?

I'd like the `prismacloud_policies` data source https://registry.terraform.io/providers/PaloAltoNetworks/prismacloud/latest/docs/data-sources/policies to include the `policySubTypes`.

### Describe the solution you'd like

I'd like to select all enabled policies, but then filter out the ones that have "build" as policySubType included.
Afterward I like to add all of the still selected policies to an alert rule.

Currently I get the following error for some rules in our setup:
`Error(msg:compute_policy_only_allowed_for_cag_rule severity:error subject:)` which is because the policy is a "build" subtype policy.

**Comment by jgrumboe** [comment]
Hi @AnushreeHS 
I saw you released 1.5.4 with subtypes support and tested it with the following datasource:
```
data "prismacloud_policies" "default" {
  filters = {
    "policy.enabled" : true,
  }
}

output "test" {
  value = data.prismacloud_policies.default.listing
}
```

I get 233 policies back.
These are the different policy_types:
    "policy_type" = "anomaly"
    "policy_type" = "attack_path"
    "policy_type" = "audit_event"
    "policy_type" = "config"
    "policy_type" = "iam"
    "policy_type" = "network"
    "policy_type" = "workload_incident"
    "policy_type" = "workload_vulnerability"

But the subtypes for all policies is just:
"policy_subtypes" = tolist(null) /* of string */

Can you fix that?

**Comment by AnushreeHS** [comment]
v1.5.4 adds support for this capability.

**Comment by jgrumboe** [comment]
Thank you, already tested it and works fine.
