### ISSUE TITLE
Cannot create a GCP cloud account

### ISSUE THREAD

**Issue by Melchizedech** [PaloAltoNetworks/terraform-provider-prismacloud#3]
## Describe the bug

It is not possible to create a GCP Cloud Acccount. 

## Expected behavior

As outlined in the documentation, https://www.terraform.io/docs/providers/prismacloud/r/cloud_account.html, I can add a GCP Cloud Account.

## Current behavior

When I add a GCP Cloud Account, I get an error : 

```
Error: 400/https://api2.eu.prismacloud.io/cloud/gcp Error(msg:invalid_gcp_project_id severity:error subject:invalid_parameter_value)

  on cloud_account.tf line 1, in resource "prismacloud_cloud_account" "cluster":
   1: resource "prismacloud_cloud_account" "cluster" {

```

resource is configured : 

```
resource "prismacloud_cloud_account" "cluster" {
  gcp {
    name       = "Test"
    account_id = "my_id"
    group_ids = [
      prismacloud_account_group.staging.id
    ]
    credentials_json = base64decode(google_service_account_key.prisma_cloud_service_account_key.private_key)
  }
}
```

## Possible solution

Use the `account_id` when creating the GCP Cloud Account ?
https://github.com/terraform-providers/terraform-provider-prismacloud/blob/master/prismacloud/resource_cloud_account.go#L314
Looks like you're using "id" which is an empty string.

## Steps to reproduce

1. using this resource
```
resource "prismacloud_cloud_account" "cluster" {
  gcp {
    name       = "Test"
    account_id = "my_id"
    group_ids = [
      prismacloud_account_group.staging.id
    ]
    credentials_json = base64decode(google_service_account_key.prisma_cloud_service_account_key.private_key)
  }
}

resource "prismacloud_account_group" "staging" {
  name        = "Staging clusters"
  description = "Group containing only staging custers"
}

resource "google_service_account_key" "prisma_cloud_service_account_key" {
  service_account_id = google_service_account.prisma_cloud_service_account.name
}

resource "google_service_account" "prisma_cloud_service_account" {
  account_id   = "prisma-cloud-serv-test-${random_string.unique_id.result}"
  display_name = "Prisma Cloud Service Account Test"
  project      = "my_id"
}

resource "random_string" "unique_id" {
  length    = 5
  min_lower = 5
  special   = false
}
```
2. add the backend/providers
```
terraform {
  backend "gcs" {}
}

provider "prismacloud" {
  protocol = "https"
  url      = "api2.eu.prismacloud.io"

}

provider "google" {}
provider "random" {}
```

3. applying this configuration will fail with
```
Error: 400/https://api2.eu.prismacloud.io/cloud/gcp Error(msg:invalid_gcp_project_id severity:error subject:invalid_parameter_value)

  on cloud_account.tf line 1, in resource "prismacloud_cloud_account" "cluster":
   1: resource "prismacloud_cloud_account" "cluster" {

```

## Context

I want to setup my platform but i can't.
this along PaloAltoNetworks/terraform-provider-prismacloud#1 is quite painful to know if 
1/ i make a mistake
2/ or the lib is flawed.

## Your Environment

- Version used: 1.0.0
- go 1.13, terraform v0.12.28
- Linux XXX 5.7.9-arch1-1 PaloAltoNetworks/terraform-provider-prismacloud-orig#1 SMP PREEMPT Thu, 16 Jul 2020 19:34:49 +0000 x86_64 GNU/Linux

**Comment by ebeuerle** [comment]
This has been fixed.
