### ISSUE TITLE
compliance standard import fails

### ISSUE THREAD

**Issue by moonman81** [PaloAltoNetworks/terraform-provider-prismacloud#39]
## Describe the bug
Unexpected error when importing a compliance standard

When attempting to import a compliance standard, I get the error:

Error: invalid character '"' after object key:value pair
 on /Users/redacted/main.tf line 1, in provider "prismacloud":
   1: provider "prismacloud" {

When running:

terraform import prismacloud_compliance_standard.this [valid guid here]

from the following terraform:

provider "prismacloud" {
  url = "api2.prismacloud.io"
  json_config_file = ".prismacloud_auth.json"
}

resource "prismacloud_compliance_standard" "this" {}

The same creds used in .prismacloud_auth.json match those validated using pc-toolbox.

## Expected behavior

should return a json document describing a compliance standard

## Current behavior

complains of invalid character '"' where there are no unbalanced quotes or invalid quotes in the terraform driving it.

## Steps to reproduce

1.
2.
3.
4.

## Your Environment

- Version used:
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3):
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by netjordan** [comment]
Hi @moonman81 

I've faced this issue before, I think it's actually a terraform/windows issue. Did you try escaping the double quotes when running the command? - for example:
`terraform import prismacloud_compliance_standard.this[\"valid guid here\"]`

This is a related report in the terraform project - [https://github.com/hashicorp/terraform/issues/22286](https://github.com/hashicorp/terraform/issues/22286)

**Comment by ebeuerle** [comment]
We have been unable to reproduce this problem.  This is likely a TF quoting issue as @netjordan indicated.
