### ISSUE TITLE
"key" shows in plaintext during Terraform plan for an Azure subscription

### ISSUE THREAD

**Issue by ZachTB123** [PaloAltoNetworks/terraform-provider-prismacloud#4]
## Describe the bug

I am trying to register an Azure subscription using the `prismacloud_cloud_account` resource. During `terraform plan`, the required `key` argument (which I believe is the Service Principal's password), is visible in plaintext.

## Expected behavior

A sensitive value like this should be be marked as sensitive during `terraform plan`.

## Current behavior

The `key` value is visible in plaintext.

## Possible solution

Like other Terraform resources that deal with sensitive values, this should be marked as sensitive.

## Steps to reproduce

1. Run `terraform plan` when working with an Azure subscription.

## Your Environment

- Version used: 1.0.0

**Comment by ebeuerle** [comment]
Fixed in v1.0.8
