### ISSUE TITLE
Support for compute functionality

### ISSUE THREAD

**Issue by rmclaughlin-nelnet** [PaloAltoNetworks/terraform-provider-prismacloud#43]
### Is your feature request related to a problem?
The current Prisma terraform provider does not support compute functionality. We found this provider https://github.com/CircleCI-Archived/terraform-provider-twistlock but it is deprecated and points us to use the official provider. Is this in your pipeline, if so how far out is it?

### Describe the solution you'd like
I would like to have compute supported by this provider.

### Describe alternatives you've considered
We have considered forking https://github.com/CircleCI-Archived/terraform-provider-twistlock and updating it ourselves.

**Comment by ebeuerle** [comment]
There are plans for a Compute provider but it will be separate from this one for time being...

**Comment by rmclaughlin-nelnet** [comment]
Thanks for the reply. Is this being worked on right now or is it still months/years/decades out? We are just trying to plan out what we are going to do while we wait and how much time we want to invest in a one off solution.

**Comment by ebeuerle** [comment]
I would guess at least 1-2 months out.

**Comment by sgordon46** [comment]
https://github.com/PaloAltoNetworks/prisma-cloud-compute-operator

**Comment by rmclaughlin-nelnet** [comment]
Is the plan for the above provider to support all the prisma cloud compute functionality?

**Comment by ebeuerle** [comment]
Yes.

**Comment by hi-artem** [comment]
I will just add this here for everyone's awareness https://github.com/PaloAltoNetworks/terraform-provider-prismacloudcompute
