### ISSUE TITLE
When using variables to provide group_ids in prismacloud_cloud_account a change is always required

### ISSUE THREAD

**Issue by netjordan** [PaloAltoNetworks/terraform-provider-prismacloud#48]
## Describe the bug

We have the terraform code:
```
resource "prismacloud_cloud_account" "account" {
  aws {
    name = var.account_tags.AccountNiceName
    account_id = data.aws_caller_identity.current.account_id
    external_id = random_uuid.external_id.result
    group_ids = ["bfc12f64-f1e8-11eb-9a03-0242ac130003", var.team_group_id, var.system_group_id]
    role_arn = aws_iam_role.prisma.arn
  }
}
```

However, on every plan/apply we get something similar to:
```
# module.account_defaults.module.prisma.prismacloud_cloud_account.account will be updated in-place
  ~ resource "prismacloud_cloud_account" "account" {
        id = "aws:12345678912"
      ~ aws {
          ~ group_ids       = [
              - "cd0e35ae-f1e8-11eb-9a03-0242ac130003",
              - "d746dcd8-f1e8-11eb-9a03-0242ac130003",
                "bfc12f64-f1e8-11eb-9a03-0242ac130003",
              + "d746dcd8-f1e8-11eb-9a03-0242ac130003",
              + "cd0e35ae-f1e8-11eb-9a03-0242ac130003",
            ]
            name            = "aws-account-12"
            # (6 unchanged attributes hidden)
        }
    }
```

## Expected behavior

I would expect it not to care about the ordering in this situation as it does not matter.

## Current behavior

Terraform will detect changes on every apply, and apply updates to the prisma cloud api. This means the apply change is applying changes unnecessarily and taking longer than it needs to.

## Steps to reproduce

I have provided code examples above, which should be able to reproduce the issue.

## Your Environment

Using version v1.1.2 of the provider and various versions of terraform on Linux.

**Comment by ebeuerle** [comment]
Fixed in next release scheduled for Friday (10/29)
