### ISSUE TITLE
prismacloud_cloud_account: group_ids order is inconsistent

### ISSUE THREAD

**Issue by AjkayAlan** [PaloAltoNetworks/terraform-provider-prismacloud#49]
## Describe the bug

Multiple group ids in the prismacloud_cloud_account - group_ids field is resulting in inconsistencies between file and state, causing reprovisions when they shouldn't.

Could this be corrected?

## Expected behavior

Defining multiple group id's should be deterministic and not cause a change between runs.

## Current behavior

I have a super simple change which enables a feature flag in one of our modules:
![image](https://user-images.githubusercontent.com/14236618/128262203-8d215e4e-9073-49c3-a5fb-10626b00f9c8.png)

This change should not affect Prisma group id's what so ever. However, I have a significant amount of accounts showing a change similar to the following (sensitive info redacted):

```
  # module.account1-baseline.prismacloud_cloud_account.account will be updated in-place
  ~ resource "prismacloud_cloud_account" "account" {
        id = "aws:123456789012"

      ~ aws {
          ~ group_ids       = [
              - "guid1",
                "guid2",
              + "guid1",
            ]
            name            = "account1"
            # (6 unchanged attributes hidden)
        }

        # (1 unchanged block hidden)
    }

  # module.account2-baseline.prismacloud_cloud_account.account will be updated in-place
  ~ resource "prismacloud_cloud_account" "account" {
        id = "aws:567890123456"

      ~ aws {
          ~ group_ids       = [
              - "guid1",
                "guid2",
              + "guid1",
            ]
            name            = "account2"
            # (6 unchanged attributes hidden)
        }

        # (1 unchanged block hidden)
    }
```

We currently define out this resource in our baseline module (which every account gets). It is defined as:
```
resource "prismacloud_cloud_account" "account" {
  aws {
    name        = data.aws_iam_account_alias.current.account_alias
    account_id  = data.aws_caller_identity.current.account_id
    external_id = local.prisma-external-id
    group_ids = sort([
      data.prismacloud_account_group.target.group_id,
      data.prismacloud_account_group.default.group_id
    ])
    role_arn = aws_iam_role.our-prisma-role.arn
  }
}
```

## Steps to reproduce

See above

## Context

This causes our terraform apply step to take drastically longer, depending on how lucky or unlucky we get. My last apply took 15 minutes for something which should have taken <5.

## Your Environment

- Version used: v1.1.2
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): GitHub Actions 
- Operating System and version (desktop or mobile): GitHub Actions - Ubuntu 20.04

**Comment by AjkayAlan** [comment]
Related to: #48. If you want to track this issue in one ticket, feel free to close mine.

**Comment by ebeuerle** [comment]
Fixed in next release scheduled for Friday (10/29)
