### ISSUE TITLE
Add an account group and associate with cloud account

### ISSUE THREAD

**Issue by sidhurana-chd** [PaloAltoNetworks/terraform-provider-prismacloud#67]
## Describe the bug

Our AWS accounts are already onboarded via Org-ID. We executed cloudformation stackset. We are facing error while adding an account group and associating with existing cloud account(s) 

## Expected behavior

Add new Account group and association with existing on-boarded account should work.

## Current behavior

Error while applying via terraform :  prismacloud_cloud_account.platform-sandbox: 1 error occurred:
	* prismacloud_cloud_account.platform-sandbox: 400/https://api2.prismacloud.io/cloud/aws Error(msg:invalid_account_group_ids severity:error subject:) 

## Steps to reproduce

Create groups.tf file with below content and pass prisma API credentials via env. vars:

 resource "prismacloud_account_group" "platform-sandbox" {
    name = "Platform Sandbox"
    description = "platform-sandbox"
}

resource "prismacloud_cloud_account" "platform-sandbox" {
    aws {
        name = "platform-sandbox"
        account_id = "AWS ACCOUNT ID"
        external_id = "PRISMA-ACCOUNT-ID"
        group_ids = [
            "AWS ACCOUNT ID",
        ]
        role_arn = "arn:aws:iam::PRISMA-ACCOUNT-ID:role/PrismaCloudReadOnlyRole"
    }
}

## Screenshots

![image](https://user-images.githubusercontent.com/90280769/133616604-a028a5e0-d3bc-4678-9e9f-a445be73c360.png)

## Context

Not able to create alert rules as creation of account groups and mapping to particular account is a pre-requisite. 

## Your Environment

Terraform v0.11.15
provider.prismacloud v1.1.2

**Comment by jasonckeating** [comment]
Just worked past an issue similar to this.
account_group_ids have to be a list of strings.

Verify the leading 0s aren't being removed from the account id list.

**Comment by sunkavillisuranya** [comment]
Hi @sidhurana-chd, 
From the terraform script you have attached for adding aws account,
resource "prismacloud_cloud_account" "platform-sandbox" {
aws {
name = "platform-sandbox"
account_id = "AWS ACCOUNT ID"
external_id = "PRISMA-ACCOUNT-ID"
group_ids = [
"AWS ACCOUNT ID",
]
role_arn = "arn:aws:iam::PRISMA-ACCOUNT-ID:role/PrismaCloudReadOnlyRole"
}
}
you assigned the aws account id for group_ids, group_ids should have account_group_id(ID of the account group created), Either ID can be given directly, or we can assign id from the account group resources as
`group_ids =[prismacloud_account_group.platform-sandbox.group_id] `
Please verify and let us know if you still face any issues. Thank you.

**Comment by sidhurana-chd** [comment]
this is resolved now. thx
