### ISSUE TITLE
Limitation of "Alerts Reports" feature by Terraform

### ISSUE THREAD

**Issue by CHARA77** [PaloAltoNetworks/terraform-provider-prismacloud#8]
We have limitation with the feature "Alerts Reports", we have based our process of alerts on this feature,  we would like to send to our Stakeholders this type of report "cloud security assessment" by Terraform but it seem not possible.

Solution :  
We would like to have "Alerts Reports" on the Terraform Provider Prisma Cloud.

**Comment by ebeuerle** [comment]
Alert reports has been added.  CSA reports can only be downloaded.
