### ISSUE TITLE
Not able to create alert rules

### ISSUE THREAD

**Issue by sidhurana-chd** [PaloAltoNetworks/terraform-provider-prismacloud#83]
## Describe the bug

Not able to create alert rules

## Expected behavior

Should be able to add alert rules.

## Current behavior
Error: Error applying plan:

1 error occurred:
	* module.prisma_notify_all_public_ips.prismacloud_alert_rule.alert_example: 1 error occurred:
	* prismacloud_alert_rule.alert_example: 403/https://api2.prismacloud.io/alert/rule Error(msg:incomplete_account_group_access severity:error subject:)

## Steps to reproduce

1. Create module (main.tf)
resource "prismacloud_alert_rule" "alert_example" {
    name = "${var.prismacloud_alert_rule_name}"
    policies = ["${var.prisma_policy_name}"]
    enabled  = "${var.is_alert_enabled}"
    allow_auto_remediate = false
    notify_on_open       = "${var.is_alert_notification_enabled}"
    target {
      account_groups = ["${var.account_groups}"]
  }
   notification_config {
      frequency = "${var.alert_frequency}"
      recipients = "${var.alert_recipients}"
      detailed_report = true
      include_remediation = true
      config_type = "${var.alert_notify_config}"
  }
    description = "Managed by Terraform"
}
2. in variables.tf
variable "prismacloud_alert_rule_name" {
  default = ""
}
variable "prisma_policy_name" {
  type = "list"
  default = [""]
}
variable "is_alert_enabled" {
  default = true
}
variable "is_alert_notification_enabled" {
  default = true
}
variable "account_groups" {
  type = "list"
  default = [""]
}
variable "alert_frequency" {
  default = ""
}
variable "alert_recipients" {
  type = "list"
  default = [""]
}
variable "alert_notify_config" {
  default = "email"
}

3.
module "prisma_notify_all_public_ips" {
  source = "./modules/prisma_alert_rules"
  prismacloud_alert_rule_name = "aws-network-interfaces-with-all-public-ips"
  prisma_policy_name = ["aws-network-interfaces-with-all-public-ips"]
  account_groups = ["IT-Accounts"]
  alert_frequency = "monthly"
  alert_recipients = ["sabc@example.com"]
}

## Context

Not able to create any alert rules.

## Your Environment

- Version used:
terraform --version
Terraform v0.11.15
+ provider.prismacloud v1.1.4

**Comment by jasonckeating** [comment]
@sidhurana-chd does your user that is executing the Terraform apply have write permissions to the account group set being acted upon?
403 is a forbidden code, so the issue is likely related to missing permissions.

**Comment by sidhurana-chd** [comment]
Figured it out. I need to pass policy ID in "prisma policy name"
e.g:   prisma_policy_name = ["6310126c-85c1-44af-bd45-fee2b71f97b8"] 
and then it worked. Strange that we naming is bit confusing. It should be "prisma_policy_id" here. 

We can close this issue.
