### ISSUE TITLE
403 incomplete_account_group_access error when creating an alert rule

### ISSUE THREAD

**Issue by colehorsman** [PaloAltoNetworks/terraform-provider-prismacloud#90]
## Describe the bug

403 error when creating an alert rule. terraform plan works, but apply results in 403.

## Expected behavior

Create alert rule and apply to target account_group "Clud-Support-Sandbox"

## Current behavior0

Error: 403/https://api2.prismacloud.io/alert/rule Error(msg:incomplete_account_group_access severity:error subject:)
│
│   with prismacloud_alert_rule.example-test-rule,
│   on alert-rule-example.tf line 14, in resource "prismacloud_alert_rule" "example-test-rule":
│   14: resource "prismacloud_alert_rule" "example-test-rule" {

## Possible solution

403 should indicate some kind of access issue, but i am using a credential with sysadmin permissions. 
The account group exists in the prisma tenant, however i am uncertain if this is the format expected. 

## Steps to reproduce

terraform {
  required_providers {
    prismacloud = {
      source = "PaloAltoNetworks/prismacloud"
      version = "1.1.5"
    }
  }
}

provider "prismacloud" {
  json_config_file = ".prismacloud_auth.json"
}

resource "prismacloud_alert_rule" "example-test-rule" {
    name = "css-pc-aws-s3-64-remediate-bucket-encryption"
    description = "Made by Terraform - Scheduled Remediation Test"
    enabled = false
    allow_auto_remediate = false
    scan_all = true
    policies = ["AWS IAM policy attached to users"]
    notify_on_open = true

target {
  account_groups = [
    "Example-Support-Sandbox"
  ]
}

notification_config {
    # day_of_month = "0"
    r_rule_schedule = ""
    # frequency_from_r_rule = ""
    # hour_of_day = "0"
    # frequency = "as_it_happens"
    enabled = false
    include_remediation = false
    recipients = ["user@domain.com"]
    config_type = "aws_s3"
  }
}

## Context

I want to codify all alert rules and add apply the alert rule to the account group at time of deployment
It would also be useful to have a meaningful example usage alert rule in the documentation as the only thing provided is:

resource "prismacloud_alert_rule" "example" {
    name = "My Alert Rule"
    description = "Made by Terraform"
}

## Your Environmen

- Version used: 1.1.5

**Comment by ebeuerle** [comment]
policies = ["AWS IAM policy attached to users"] **(this needs to be a policy id)**


target {
account_groups = [
"Example-Support-Sandbox" **(this needs to be a acct grp id)**
]

**Comment by colehorsman** [comment]
Can you give me example of policy Id and account group Id format?

**Comment by ebeuerle** [comment]
Typical uuid type format...
