### ISSUE TITLE
Can't specify attributes when creating an alert rule

### ISSUE THREAD

**Issue by colehorsman** [PaloAltoNetworks/terraform-provider-prismacloud#92]
## Describe the bug

Can't specify attributes when creating an alert rule

## Expected behavior

  notification_channels = [
    "aws_s3"
  ] 

results in "unsupported argument"

from the api documentation "integrationConfig":{"s3Uri":"s3://bucket-example/folder" i need to specify this s3 uri for the alert rule integration but i don't see where the terraform documentation shows how to specify this value. 

Ive tried putting notification_channel in resource block and notification_config but neither are accepted. 

  ### Current behavior

Error: "notification_channels": this field cannot be set
│
│   with prismacloud_alert_rule.example-test-rule,
│   on alert-rule-example.tf line 14, in resource "prismacloud_alert_rule" "example-test-rule":
│   14: resource "prismacloud_alert_rule" "example-test-rule" {

## Possible solution

likely i am not referencing the attributes correctly. 

## Steps to reproduce

terraform {
  required_providers {
    prismacloud = {
      source = "PaloAltoNetworks/prismacloud"
      version = "1.1.5"
    }
  }
}

provider "prismacloud" {
  json_config_file = ".prismacloud_auth.json"
}

resource "prismacloud_alert_rule" "example-test-rule" {
    name = "css-pc-aws-s3-64-remediate-bucket-encryption"
    description = "Made by Terraform - Scheduled Remediation Test"
    enabled = false
    allow_auto_remediate = false
    scan_all = false
 # notification_channels = [
    #   "aws_s3"
    # ] 

 # RDS instance is not encrypted - 34fa9efb-d18f-41e4-b93f-2f7e5378752c   
    policies = [
      "policyid"
      ] 
    notify_on_open = true

# Account Group Cloud Support Sandbox 

target {
  account_groups = [
    "account-group-id"
  ]
}

notification_config {
    # day_of_month = "0"
    r_rule_schedule = ""
    # frequency_from_r_rule = ""
    # hour_of_day = "0"
    # frequency = "as_it_happens"
    enabled = false
    include_remediation = false
    recipients = ["this is where i specified the integration id"]
    config_type = "aws_s3"
  }
}

## Context

I am trying to create an alert rule which will send an email to myself as well as trigger an s3 notification channel and specify a particular s3 uri.

## Your Environment
this is the api re

{"id":"ezample-id","name":"css_remediate_cmk_rotation_60_days","integrationType":"aws_s3","integrationConfig":{"s3Uri":"s3://example-bucket/example-folder","region":"us-east-1","roleArn":"arn:aws:iam::accountnumber:role/prisma-s3-integration-test","externalId":"external-id-value","rollUpInterval":60},"description":"sets auto rotate to true","enabled":true,"createdBy":"user@domain.com","createdTs":value,"lastModifiedBy":"user@domain.com","lastModifiedTs":value,"status":"NA","reason":{"lastUpdated":0},"valid":true},

**Comment by netjordan** [comment]
Hey,

The attribute 'notification_channels' is actually an output of the resource, rather than an argument that can be used as input. You should specify the integration id in the notification_config -> recipients list, as you have in your example, and you do not need to specify the notification_channels attribute.

 I think what you need is something like this:

```
resource "prismacloud_alert_rule" "example-test-rule" {
  name = "css-pc-aws-s3-64-remediate-bucket-encryption"
  description = "Made by Terraform - Scheduled Remediation Test"
  enabled = true
  allow_auto_remediate = false
  scan_all = false
  target {
    account_groups = [
      "account-group-id"
    ]
  }

  notification_config {
    enabled = true
    include_remediation = false
    recipients = ["id here"]
    config_type = "aws_s3"
  }
}
```

To make sure your posts in Github format well, you might want to surround code snippets with three backticks (`), or you can hit the code <> button in the editor.

Thanks!
