### ISSUE TITLE
Policy argument "enabled" doesn't close open alerts

### ISSUE THREAD

**Issue by iokush** [PaloAltoNetworks/terraform-provider-prismacloud#93]
## Describe the bug

While updating the `enabled` argument to false for an existing policy, the open alerts aren't closed.

## Expected behavior

Any open alerts should be resolved if `enabled = false` is set.

## Current behavior

Currently, the open alerts aren't closed while setting the `enabled` argument while if the same action is done via the Prisma Cloud console UI - the open alerts are closed.

## Steps to reproduce

1. Have a policy with active "Open" alerts
2. Set the `enabled = false`

```
resource "prismacloud_policy" "example" {
    name = "My Policy"
    policy_type = "network"
    enabled = false
    rule {
        name = "my rule"
        criteria = "savedSearchId"
        parameters = {
            "savedSearch": "true",
            "withIac": "false",
        }
        rule_type = "Network"
    }
}
```

## Your Environment

- Version used: Terraform v1.0.11,  paloaltonetworks/prismacloud v1.1.4

**Comment by ebeuerle** [comment]
@iokush Can you provide the output from your tf apply?

**Comment by iokush** [comment]
@ebeuerle The tf apply goes through as usual (no errors/warnings) but the already open alerts for the policy don't get resolved - is there anything specific you need from the tf apply output?

**Comment by ebeuerle** [comment]
If the policy is marked disabled, then TF is working and the issue is with the underlying Prisma Cloud platform.   I would suggest opening a support ticket with Prisma Cloud support team.
