### ISSUE TITLE
Populating Dynamic Groups through PAN and Terraform 

### ISSUE THREAD

**Issue by Montana** [PaloAltoNetworks/terraform-provider-prismacloud#99]
Hey PAN,

I've ran `type=version` and requested the version type to show in a verbose esque manner on `PAN-OS`. I've been setting this up in conjunction with HashiCorp Terraform. It currently looks like this:

```hcl
resource "panos_dynamic_user_group" "example" {
    name = "montanatest1"
    description = "PAN and Terraform"
    filter = "'orange'"
}
```
This is mainly using `panos_dynamic_user_group`, what I want to do is set up another machine do some flavor of a cron job and or a cron table,  which I could SSH into the appliance and reboot it.

Is this feasible?
						
Thank you so much!
Cheers,
Montana Mendy

**Comment by trishala1999** [comment]
@Montana This issue is related to the panos terraform provider and not to the prisma cloud. Please report it here https://github.com/PaloAltoNetworks/terraform-provider-panos

**Comment by Montana** [comment]
Ah, sorry about that @trishala1999, will do.
